name: example-make-lib
base: core22
version: '0.1'
summary: An example snap for a Makefile project using a system library
description: |
  Shows how to create a snap for an application that uses a Makefile for
  build and installation.

grade: devel
confinement: classic

apps:
  make-example:
    command: bin/example-make-lib

### Note: enable-patchelf only does not work for core22 with the stable channel of snapcraft 7.2.

parts:
  make-example-part:
    build-packages:
      - wget2-dev
    plugin: make
    build-attributes:
     - enable-patchelf
    source: .
